name: ubuntu

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install other dependencies
        run: |
          set -eux
          sudo apt install -y llvm-7 clang-7 libgc-dev
      - name: Output versions
        run: |
          set -eux
          rustc --version
          cargo --version
          llc-7 --version
          clang-7 --version
      - name: Build and test
        run: |
          set -eux
          env -- LLC=llc-7 CLANG=clang-7 cargo test
